### Producción:

### Ruta para listar todos los blogs:
GET https://full-stack-open-parte-13.onrender.com/api/blogs

### Ruta para listar todos los blogs (Filtro de busqueda en "title"):
GET https://full-stack-open-parte-13.onrender.com/api/blogs?search=test

### Ruta para listar todos los blogs (Filtro de busqueda en "author"):
GET http://localhost:3001/api/blogs?search=Diri

### Ruta para adicionar un nuevo blog.
POST https://full-stack-open-parte-13.onrender.com/api/blogs
Content-Type: application/json
Authorization: Bearer ingresareltokenaquí

{
  "author": "DiriARG",
  "url": "https://www.google.com/",
  "title": "Eliminar con token"
}

### Ruta para eliminar un blog.
DELETE https://full-stack-open-parte-13.onrender.com/api/blogs/16
Authorization: Bearer ingresareltokenaquí

### Ruta para actualizar un blog.
PUT https://full-stack-open-parte-13.onrender.com/api/blogs/8
Content-Type: application/json

{
  "likes": 3
}

### Ruta para agregar un nuevo usuario.
POST https://full-stack-open-parte-13.onrender.com/api/users
Content-Type: application/json

{
  "username": "Testproduccion@gmail.com",
  "name": "Matías Di Risio"
}

### Ruta para listar todos los usuarios:
GET https://full-stack-open-parte-13.onrender.com/api/users

### Ruta para cambiar nombre de usuario.
PUT https://full-stack-open-parte-13.onrender.com/api/users/DiriARG
Content-Type: application/json

{
  "username": "Diriabz"
}

### Ruta para inicar sesión.
POST https://full-stack-open-parte-13.onrender.com/api/login
Content-Type: application/json

{
  "username": "Testproduccion@gmail.com",
  "password": "secret"
}









### Desarrollo:

### Ruta para listar todos los blogs:
GET http://localhost:3001/api/blogs

### Ruta para listar todos los blogs (Filtro de busqueda en "title"):
GET http://localhost:3001/api/blogs?search=test

### Ruta para listar todos los blogs (Filtro de busqueda en "author"):
GET http://localhost:3001/api/blogs?search=Diri

### Ruta para adicionar un nuevo blog.
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer ingresareltokenaquí 

{
  "author": "DiriARG",
  "url": "https://www.google.com/",
  "title": "Test ejercicio 13.10 v3"
}

### Ruta para eliminar un blog.
DELETE http://localhost:3001/api/blogs/14
Authorization: Bearer ingresareltokenaquí 

### Ruta para actualizar un blog.
PUT http://localhost:3001/api/blogs/1
Content-Type: application/json

{
  "likes": 3
}

### Ruta para agregar un nuevo usuario.
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "DiriARG@gmail.com",
  "name": "Matías Di Risio"
}

### Ruta para listar todos los usuarios:
GET http://localhost:3001/api/users

### Ruta para cambiar nombre de usuario.
PUT http://localhost:3001/api/users/DiriARG
Content-Type: application/json

{
  "username": "Diriabz"
}

### Ruta para inicar sesión.
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "DiriARG@gmail.com",
  "password": "secret"
}