### Producción:

### Ruta para listar todos los blogs:
GET https://full-stack-open-parte-13.onrender.com/api/blogs

### Ruta para listar todos los blogs (Filtro de busqueda en "title"):
GET https://full-stack-open-parte-13.onrender.com/api/blogs?search=probando

### Ruta para listar todos los blogs (Filtro de busqueda en "author"):
GET http://localhost:3001/api/blogs?search=Diri

### Ruta para adicionar un nuevo blog.
POST https://full-stack-open-parte-13.onrender.com/api/blogs
Content-Type: application/json
Authorization: Bearer ingresareltokenaquí

{
  "author": "DiriARG",
  "url": "https://www.google.com/",
  "title": "Probando migraciones en producción",
  "year": 2026
}

### Ruta para eliminar un blog.
DELETE https://full-stack-open-parte-13.onrender.com/api/blogs/16
Authorization: Bearer ingresareltokenaquí

### Ruta para actualizar un blog.
PUT https://full-stack-open-parte-13.onrender.com/api/blogs/8
Content-Type: application/json

{
  "likes": 3
}

### Ruta para agregar un nuevo usuario.
POST https://full-stack-open-parte-13.onrender.com/api/users
Content-Type: application/json

{
  "username": "Testproduccion@gmail.com",
  "name": "Matías Di Risio"
}

### Ruta para listar todos los usuarios:
GET https://full-stack-open-parte-13.onrender.com/api/users

### Ruta para cambiar nombre de usuario.
PUT https://full-stack-open-parte-13.onrender.com/api/users/Testproduccion@gmail.com
Content-Type: application/json

{
  "username": "TestProduccion@gmail.com"
}

### Ruta para inicar sesión.
POST https://full-stack-open-parte-13.onrender.com/api/login
Content-Type: application/json

{
  "username": "Testproduccion@gmail.com",
  "password": "secret"
}

### Ruta de autores: Cantidad total de blogs y número total de likes.
GET https://full-stack-open-parte-13.onrender.com/api/authors

### Ruta para enlazar el id del usuario con el id del blog.
POST https://full-stack-open-parte-13.onrender.com/api/readinglists
Content-Type: application/json

{
  "blogId": 2,
  "usuarioId": 1
}

### Ruta para obtener un usuario y su lista de lectura.
GET https://full-stack-open-parte-13.onrender.com/api/users/1?read=false

### Ruta para marcar blog como leído.
PUT https://full-stack-open-parte-13.onrender.com/api/readinglists/1
Content-Type: application/json
Authorization: Bearer ingresareltokenaquí

{
  "read": true
}

### Ruta para que el usuario pueda cerrar sesión (simplemente ingrese el token).
DELETE https://full-stack-open-parte-13.onrender.com/api/logout
Authorization: Bearer ingresareltokenaquí










### Desarrollo:

### Ruta para listar todos los blogs:
GET http://localhost:3001/api/blogs

### Ruta para listar todos los blogs (Filtro de busqueda en "title"):
GET http://localhost:3001/api/blogs?search=test

### Ruta para listar todos los blogs (Filtro de busqueda en "author"):
GET http://localhost:3001/api/blogs?search=Diri

### Ruta para adicionar un nuevo blog.
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer ingresareltokenaquí

{
  "author": "DiriARG",
  "url": "https://www.google.com/",
  "title": "Ejercicio 10.23",
  "year": 2026
}

### Ruta para eliminar un blog.
DELETE http://localhost:3001/api/blogs/14
Authorization: Bearer ingresareltokenaquí 

### Ruta para actualizar un blog.
PUT http://localhost:3001/api/blogs/1
Content-Type: application/json

{
  "likes": 3
}

### Ruta para agregar un nuevo usuario.
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "DiriARG@gmail.com",
  "name": "Matías Di Risio"
}

### Ruta para listar todos los usuarios:
GET http://localhost:3001/api/users

### Ruta para cambiar nombre de usuario.
PUT http://localhost:3001/api/users/DiriARG
Content-Type: application/json

{
  "username": "Diriabz"
}

### Ruta para inicar sesión.
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "DiriARG@gmail.com",
  "password": "secret"
}


### Ruta de autores: Cantidad total de blogs y número total de likes.
GET http://localhost:3001/api/authors

### Ruta para enlazar el id del usuario con el id del blog.
POST http://localhost:3001/api/readinglists
Content-Type: application/json

{
  "blogId": 2,
  "usuarioId": 1
}

### Ruta para obtener un usuario y su lista de lectura.
GET http://localhost:3001/api/users/1?read=false

### Ruta para marcar blog como leído.
PUT http://localhost:3001/api/readinglists/1
Content-Type: application/json
Authorization: Bearer ingresareltokenaquí

{
  "read": true
}

### Ruta para que el usuario pueda cerrar sesión (simplemente ingrese el token).
DELETE http://localhost:3001/api/logout
Authorization: Bearer ingresareltokenaquí

